const helpers = require('../helpers/auth.helper')
const userRouter = require('./users.js')
const tutorRouter = require('./tutors.js')
const courseRouter = require('./courses.js')
const authRouter = require('./auth.js')
const adminRouter = require('./admin.js')
const chatRouter = require('./chat.js')
const errorRouter = require('./error.js')
const { authenticated, authenticatedAdmin } = require('../middleware/auth.js')

module.exports = (app, passport) => {
  app.use((req, res, next) => {
    res.locals.success_messages = req.flash('success_messages')
    res.locals.error_messages = req.flash('error_messages')
    res.locals.user = helpers.getUser(req)?.toJSON()
    next()
  })
  authRouter(app, passport)
  app.use('/apple', authenticatedAdmin, adminRouter)
  app.use('/chat', authenticated, chatRouter)
  app.use('/tutors', tutorRouter)
  app.use(authenticated, userRouter)
  app.use(courseRouter)
  app.use(errorRouter)
}